This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./dissertation.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (912 entries accepted, 0 rejected).
Sorting entries..........done (9902 comparisons).
Generating output file dissertation.acr....done (371 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
